name: yuvvanraj
description: "Professional Portfolio"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8

  get: ^4.7.2
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
